# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$username$hostname • $directory $git_branch
$character
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[• ](bold fg:#fab6ad) "
error_symbol = "[• 󰅙](bold fg:red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg:#ffb4ab fg:#620f0d"
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""
format = "• [](bold bg:transparent fg:#ffb4ab)[$symbol $branch(:$remote_branch)](fg:#620f0d bg:#ffb4ab)[ ](bold bg:transparent fg:#ffb4ab)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](#ffb4ab)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[/$hostname](bg:#ffb4ab bold fg:#620f0d)[](bold fg:#ffb4ab )"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed #ffb4ab"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:#ffb4ab fg:#620f0d"
style_root = "red bold"
format = "[](bold bg:transparent fg:#ffb4ab)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#ffb4ab fg:#620f0d"
truncation_length = 6
truncation_symbol = "••/"
format = '[](bold bg:transparent fg:#ffb4ab)[$path ]($style)[](bold bg:transparent fg:#ffb4ab)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "

[cmd_duration]
min_time = 0
format = '[](bold bg:transparent fg:#ffb4ab)[ $duration](bold bg:#ffb4ab fg:#620f0d)[](bold bg:transparent fg:#ffb4ab) •• '
