-- $lock_cmd = pidof hyprlock || hyprlock
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local lock_cmd = "noctalia msg session lock"
local suspend_cmd = "pidof steam || systemctl suspend || loginctl suspend"

hl.config({
  general = {
    lock_cmd = lock_cmd,
    before_sleep_cmd = lock_cmd,
  },
})
