-- $lock_cmd = pidof hyprlock || hyprlock
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local lock_cmd = "qs -c noctalia-shell ipc call lockScreen lock"
local suspend_cmd = "pidof steam || systemctl suspend || loginctl suspend"

-- TODO: manual review — unknown section 'listener {' on line 10

-- TODO: manual review — unknown section 'listener {' on line 15

-- TODO: manual review — unknown section 'listener {' on line 21
hl.config({
    general = {
        lock_cmd = lock_cmd,
        before_sleep_cmd = lock_cmd,
    },
})

