-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
  general = {
    col = {
      active_border = "rgba(E6E2DD39)",
      inactive_border = "rgba(93908C30)",
    },
  },
  misc = {
    background_color = "rgba(141311FF)",
  },
})
