-- ######### Input method ##########
-- See https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("QT_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
-- env = GTK_IM_MODULE, wayland   # Crashes electron apps in xwayland
-- env = GTK_IM_MODULE, fcitx     # My Gtk apps no longer require this to work with fcitx5 hmm
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("GLFW_IM_MODULE", "ibus")
hl.env("INPUT_METHOD", "fcitx")

-- ############ Themes #############
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

-- ######## Toolkit backends ########
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("GTK_BACKEND", "wayland")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- ####### XDG specifications #######
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- ######## Screen tearing #########
-- env = WLR_DRM_NO_ATOMIC, 1

-- ######## Virtual envrionment #########
hl.env("XDG_STATE_HOME", os.getenv("HOME") .. "/.local/state")

-- ############ Others #############
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")
