-- Bar, wallpaper
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- exec-once = /usr/lib/geoclue-2.0/demos/agent & gammastep
-- Deprecated by Caelestia Shell
-- exec-once = ~/.config/caelestia/scripts/idle-inhibitor.sh &
-- exec-once = caelestia shell &

-- Applets
-- exec-once = ~/.config/caelestia/scripts/gammastep-applet.py &

-- Input method

-- Core components (authentication, lock screen, notification daemon)
-- exec-once = systemctl --user enable --now hyprpolkitagent.service

-- Audio

-- Clipboard: history
-- exec-once = wl-paste --watch cliphist store &

-- Cursor

hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon --format xrgb")
    hl.exec_cmd("qs -c noctalia-shell")
    hl.exec_cmd("blueman-applet &")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
end)

