-- Lines starting with #! are section headings
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Audio controls
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("SUPER+SHIFT + M", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioRaiseVolume",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 10%+"),
  { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-"),
  { locked = true, repeating = true })

--#! General
hl.bind("SUPER + Q", hl.dsp.exec_cmd("foot"))
hl.bind("SUPER+SHIFT + Q", hl.dsp.exec_cmd("foot --title floating-foot"))

hl.bind("SUPER + O", hl.dsp.exec_cmd("obsidian"))
hl.bind("SUPER + T", hl.dsp.exec_cmd("qutebrowser"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("foot"))

hl.bind("SUPER+SHIFT + V", hl.dsp.exec_cmd("vesktop --user-agent-os windows"))

-- bind = SUPER, Space, hyprexpo:expo, toggle

--#! Actions
-- Source: ./per-desktop-binds/noctalia.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.per-desktop-binds.noctalia")

-- Screenshot, Record, OCR, Color picker, Clipboard history
hl.bind("CTRL+SUPER + V",
  hl.dsp.exec_cmd("pkill fuzzel || cliphist list | fuzzel  --match-mode fzf --dmenu | cliphist decode | wl-copy"))
hl.bind("SUPER + Period", hl.dsp.exec_cmd("pkill fuzzel || ~/.local/bin/fuzzel-emoji"))
hl.bind("CTRL+SHIFT+ALT + Delete", hl.dsp.exec_cmd("pkill wlogout || wlogout -p layer-shell"))
hl.bind("CTRL+SUPER + P", hl.dsp.exec_cmd("~/.config/hypr/scripts/grimblast.sh --freeze copy area"))
hl.bind("SUPER+SHIFT + P", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
-- OCR
hl.bind("CTRL+SUPER+SHIFT + S",
  hl.dsp.exec_cmd(
    "grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l eng \"tmp.png\" - | wl-copy && rm \"tmp.png\""))
-- Color picker
hl.bind("SUPER+SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))
-- Fullscreen screenshot
hl.bind("CTRL+SUPER + P",
  hl.dsp.exec_cmd(
    "mkdir -p ~/Pictures/Screenshots && ~/.config/hypr/scripts/grimblast.sh copysave screen ~/Pictures/Screenshots/Screenshot_\"$(date '+%Y-%m-%d_%H.%M.%S')\".png"),
  { locked = true })
-- Recording stuff
hl.bind("SUPER+ALT + R", hl.dsp.exec_cmd("~/.config/hypr/scripts/record-script.sh"))
hl.bind("CTRL+ALT + R", hl.dsp.exec_cmd("~/.config/hypr/scripts/record-script.sh --fullscreen"))
hl.bind("SUPER+CTRL+ALT + R", hl.dsp.exec_cmd("~/.config/hypr/scripts/record-script.sh --fullscreen-sound"))

--!
--#! Window management
-- Focusing
--/# bind = SUPER, ←/↑/→/↓,, # Move focus in direction
hl.bind("SUPER + Left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + Right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + Up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + Down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + BracketLeft", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + BracketRight", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER+SHIFT+ALT + Q", hl.dsp.exec_cmd("hyprctl kill"))
hl.bind("ALT + TAB", hl.dsp.focus({ last = true }))
--#! Window arrangement
--/# bind = SUPER+SHIFT, ←/↑/→/↓,, # Window: move in direction
hl.bind("SUPER+SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER+SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER+SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER+SHIFT + Down", hl.dsp.window.move({ direction = "d" }))
-- Window split ratio
--/# binde = SUPER, +/-,, # Window: split ratio +/- 0.1
-- binde = SUPER, Minus, splitratio, -0.1
-- binde = SUPER, Equal, splitratio, +0.1
-- binde = SUPER, Semicolon, splitratio, -0.1
-- binde = SUPER, Apostrophe, splitratio, +0.1
-- Positioning mode
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
-- hl.bind("SUPER+ALT + F", hl.dsp.window.fullscreen_state("0 3"))
hl.bind("SUPER + F", hl.dsp.window.fullscreen(0))
hl.bind("SUPER + D", hl.dsp.window.fullscreen(1))

--!
--#! Workspace navigation
-- Switching
--/# bind = SUPER, Hash,, # Focus workspace # (1, 2, 3, 4, ...)
hl.bind("SUPER + 1", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 1"))
hl.bind("SUPER + 2", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 2"))
hl.bind("SUPER + 3", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 3"))
hl.bind("SUPER + 4", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 4"))
hl.bind("SUPER + 5", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 5"))
hl.bind("SUPER + 6", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 6"))
hl.bind("SUPER + 7", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 7"))
hl.bind("SUPER + 8", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 8"))
hl.bind("SUPER + 9", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 9"))
hl.bind("SUPER + 0", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh focus workspace 10"))

--/# bind = SUPER, Scroll ↑/↓,, # Workspace: focus left/right
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = -1 }))
hl.bind("CTRL+SUPER + mouse_up", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + mouse_down", hl.dsp.focus({ workspace = "r-1" }))
--/# bind = CTRL+SUPER, ←/→,, # Workspace: focus left/right
hl.bind("CTRL+SUPER + Right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + Left", hl.dsp.focus({ workspace = "r-1" }))
--/# bind = CTRL+SUPER+ALT, ←/→,, # Workspace: focus non-empty left/right
hl.bind("CTRL+SUPER+ALT + Right", hl.dsp.focus({ workspace = "m+1" }))
hl.bind("CTRL+SUPER+ALT + Left", hl.dsp.focus({ workspace = "m-1" }))
--/# bind = SUPER, Page_↑/↓,, # Workspace: focus left/right
hl.bind("SUPER + Page_Down", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + Page_Up", hl.dsp.focus({ workspace = -1 }))
hl.bind("CTRL+SUPER + Page_Down", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + Page_Up", hl.dsp.focus({ workspace = "r-1" }))
--# Special
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special(""))
hl.bind("SUPER+SHIFT + S", hl.dsp.window.move({ workspace = "special" }))
hl.bind("SUPER + mouse:275", hl.dsp.workspace.toggle_special(""))

--#! Workspace management
-- Move window to workspace SUPER + ALT + [0-9]
--/# bind = SUPER+ALT, Hash,, # Window: move to workspace # (1, 2, 3, 4, ...)
hl.bind("SUPER+SHIFT + 1", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 1"))
hl.bind("SUPER+SHIFT + 2", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 2"))
hl.bind("SUPER+SHIFT + 3", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 3"))
hl.bind("SUPER+SHIFT + 4", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 4"))
hl.bind("SUPER+SHIFT + 5", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 5"))
hl.bind("SUPER+SHIFT + 6", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 6"))
hl.bind("SUPER+SHIFT + 7", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 7"))
hl.bind("SUPER+SHIFT + 8", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 8"))
hl.bind("SUPER+SHIFT + 9", hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 9"))
hl.bind("SUPER+SHIFT + 0",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/hyprland/workspace_action.sh movetoworkspacesilent 10"))

hl.bind("CTRL+SUPER+SHIFT + Up", hl.dsp.window.move({ workspace = "special", silent = true }))

hl.bind("CTRL+SUPER+SHIFT + Right", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("CTRL+SUPER+SHIFT + Left", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("CTRL+SUPER + BracketLeft", hl.dsp.focus({ workspace = -1 }))
hl.bind("CTRL+SUPER + BracketRight", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CTRL+SUPER + Up", hl.dsp.focus({ workspace = "r-5" }))
hl.bind("CTRL+SUPER + Down", hl.dsp.focus({ workspace = "r+5" }))
--/# bind = SUPER+SHIFT, Scroll ↑/↓,, # Window: move to workspace left/right
hl.bind("SUPER+SHIFT + mouse_down", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("SUPER+SHIFT + mouse_up", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("SUPER+ALT + mouse_down", hl.dsp.window.move({ workspace = -1 }))
hl.bind("SUPER+ALT + mouse_up", hl.dsp.window.move({ workspace = "+1" }))
--/# bind = SUPER+SHIFT, Page_↑/↓,, # Window: move to workspace left/right
hl.bind("SUPER+ALT + Page_Down", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("SUPER+ALT + Page_Up", hl.dsp.window.move({ workspace = -1 }))
hl.bind("SUPER+SHIFT + Page_Down", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("SUPER+SHIFT + Page_Up", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("SUPER+ALT + S", hl.dsp.window.move({ workspace = "special", silent = true }))
hl.bind("SUPER + P", hl.dsp.window.pin())

hl.bind("CTRL+SUPER + S", hl.dsp.workspace.toggle_special(""))

-- Testing
hl.bind("SUPER+ALT + f12",
  hl.dsp.exec_cmd(
    "notify-send 'Test notification' \"Here's a really long message to test truncation and wrapping\\nYou can middle click or flick this notification to dismiss it!\" -a 'Shell' -A \"Test1=I got it!\" -A \"Test2=Another action\" -t 5000"))
hl.bind("SUPER+ALT + Equal",
  hl.dsp.exec_cmd("notify-send \"Urgent notification\" \"Ah hell no\" -u critical -a 'Hyprland keybind'"))

--#! Media
hl.bind("SUPER+SHIFT + N",
  hl.dsp.exec_cmd(
    "playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"),
  { locked = true })
hl.bind("XF86AudioNext",
  hl.dsp.exec_cmd(
    "playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"),
  { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("SUPER+SHIFT+ALT + mouse:275", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("SUPER+SHIFT+ALT + mouse:276",
  hl.dsp.exec_cmd(
    "playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"))
hl.bind("CTRL+SHIFT + B", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("CTRL+SHIFT + P", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

--!
--#! Apps
hl.bind("SUPER + B", hl.dsp.exec_cmd("zen-browser"))
hl.bind("SUPER + I", hl.dsp.exec_cmd("XDG_CURRENT_DESKTOP=\"gnome\" gnome-control-center"))
-- bind = CTRL+SUPER, V, exec, pavucontrol # Launch pavucontrol (volume mixer)
hl.bind("CTRL+SHIFT + Escape", hl.dsp.exec_cmd("gnome-system-monitor"))
hl.bind("SUPER+ALT + Slash", hl.dsp.exec_cmd("pkill fuzzel || fuzzel"))

hl.on("config.reloaded", function()
  hl.exec_cmd("hyprctl dispatch submap global")
end)
