-- ######## Window rules ########

-- General rule – disable blur for all windows.
-- (Using "class:.*" as a catch-all field since at least one field is required)
-- windowrule = no_blur on, match:class .*
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
  match = {
    class = "^(foot)$",
  },
  opacity = 0.95,
  no_blur = true
})

-- Uncomment to apply global transparency to all windows:
hl.window_rule({
  match = {
    class = ".*",
  },
  opacity = "0.89 override",
})

-- Floating
hl.window_rule({
  match = {
    class = "^(blueberry\\.py)$",
  },
  float = true,
})

hl.window_rule({
  match = {
    title = "^(floating-foot)$",
  },
  float = true,
  size = "(monitor_w*0.25) (monitor_h*0.4)",
  move = "cursor_x cursor_y",
})

hl.window_rule({
  match = {
    class = "^(blueman-sendto)$",
  },
  float = true,
  center = true,
  size = "(monitor_w*0.66) (monitor_h*0.66)",
})

hl.window_rule({
  match = {
    class = "^(timeshift-gtk)$",
  },
  float = true,
  center = true,
  size = "(monitor_w*0.66) (monitor_h*0.66)",
})

hl.window_rule({
  match = {
    class = "^(org.gnome.NetworkDisplays)$",
  },
  float = true,
  center = true,
  size = "(monitor_w*0.66) (monitor_h*0.66)",
})

hl.window_rule({
  match = {
    class = "^(org.gnome.Nautilus)$",
  },
  float = true,
  center = true,
  size = "(monitor_w*0.66) (monitor_h*0.66)",
})

hl.window_rule({
  match = {
    class = "^(de.haeckerfelix.Fragments)$",
  },
  float = true,
  center = true,
  size = "(monitor_w*0.5) (monitor_h*0.66)",
})

hl.window_rule({
  match = {
    title = "^(Open Torrents)$",
  },
  float = true,
  center = true,
  size = "(monitor_w*0.45) (monitor_h*0.45)",
})

hl.window_rule({
  match = {
    class = "^(pavucontrol)$",
  },
  float = true,
  size = "(monitor_w*0.45) (monitor_h*0.45)",
  center = true,
})

hl.window_rule({
  match = {
    class = "^(DesktopEditors)$",
  },
  float = true,
  size = "(monitor_w*0.2) (monitor_h*0.15)",
  center = true,
})

hl.window_rule({
  match = {
    initial_title = "^(Open Document)$",
  },
  float = true,
  size = "(monitor_w*0.45) (monitor_h*0.45)",
  center = true,
})

hl.window_rule({
  match = {
    class = "^(org.pulseaudio.pavucontrol)$",
  },
  float = true,
  size = "(monitor_w*0.45) (monitor_h*0.45)",
  center = true,
})

hl.window_rule({
  match = {
    class = "^(nm-connection-editor)$",
  },
  float = true,
  size = "(monitor_w*0.45) (monitor_h*0.45)",
  center = true,
})

hl.window_rule({
  match = {
    class = "^(org.gnome.Settings)$",
  },
  float = true,
  center = true,
  size = "(monitor_w*0.66) (monitor_h*0.66)",
})

hl.window_rule({
  match = {
    class = "^(steam_app_244210)$",
  },
  float = true,
})

-- Tiling
hl.window_rule({
  match = {
    class = "^dev\\.warp\\.Warp$",
  },
  tile = true
})

hl.window_rule({
  match = {
    class = "^(steam)$",
  },
  tile = true
})

-- Picture-in-Picture
hl.window_rule({
  match = {
    title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
  },
  float = true,
  keep_aspect_ratio = true,
  move = "((monitor_w*0.66)) ((monitor_h*0.66))",
  size = "(monitor_w*0.33) (monitor_h*0.33)",
  pin = true,
})

-- Dialog windows – float+center these windows.
hl.window_rule({
  match = {
    title = "^(Open File)(.*)$",
  },
  center = true,
  float = true,
  size = "(monitor_w*0.6) (monitor_h*0.6)",
})

hl.window_rule({
  match = {
    title = "^(Select a File)(.*)$",
  },
  center = true,
  float = true,
  size = "(monitor_w*0.6) (monitor_h*0.6)",
})

hl.window_rule({
  match = {
    title = "^(Choose wallpaper)(.*)$",
  },
  center = true,
  float = true,
  size = "(monitor_w*0.6) (monitor_h*0.6)",
})

hl.window_rule({
  match = {
    title = "^(Open Folder)(.*)$",
  },
  center = true,
  float = true,
  size = "(monitor_w*0.6) (monitor_h*0.6)",
})

hl.window_rule({
  match = {
    title = "^(Save As)(.*)$",
  },
  center = true,
  float = true,
  size = "(monitor_w*0.6) (monitor_h*0.6)",
})

hl.window_rule({
  match = {
    title = "^(Library)(.*)$",
  },
  center = true,
  float = true,
  size = "(monitor_w*0.6) (monitor_h*0.6)",
})

hl.window_rule({
  match = {
    title = "^(File Upload)(.*)$",
  },
  center = true,
  float = true,
  size = "(monitor_w*0.6) (monitor_h*0.6)",
})

-- --- Tearing ---
hl.window_rule({
  match = {
    title = ".*\\.exe",
  },
  immediate = true,
})

hl.window_rule({
  match = {
    class = "^(steam_app)",
  },
  immediate = true,
})

-- No shadow for tiled windows (matches windows that are not floating).
hl.window_rule({
  match = {
    float = 0,
  },
  no_shadow = true
})

-- ######## Layer rules ########
hl.layer_rule({
  match = { namespace = "match:class .*" },
  xray = true
})

-- layerrule = noanim, .*
hl.layer_rule({
  match = { namespace = "match:class walker" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "match:class selection" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "match:class overview" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "match:class anyrun" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "match:class indicator.*" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "match:class osk" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "match:class hyprpicker" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "ignore_alpha 0.6" },
  blur = true
})

hl.layer_rule({
  match = { namespace = "match:namespace noanim" },
  no_anim = true
})

hl.layer_rule({
  match = { namespace = "ignore_alpha 0" },
  blur = true
})

hl.layer_rule({
  match = { namespace = "ignore_alpha 0.5" },
  blur = true
})

hl.layer_rule({
  match = { namespace = "ignore_alpha 0.69" },
  blur = true
})

hl.layer_rule({
  match = { namespace = "match:namespace logout_dialog" },
  blur = true
})

-- Fullscreen
hl.window_rule({
  match = {
    class = "^(org.qutebrowser.qutebrowser)$",
  },
  maximize = true,
})

-- Workspaces
hl.window_rule({
  match = {
    class = "gcr-prompter",
  },
  workspace = "10 silent",
})

hl.window_rule({
  match = {
    title = "^(Zen Browser)$",
  },
  workspace = "3",
})

hl.window_rule({
  match = {
    class = "^(de.haeckerfelix.Fragments)$",
  },
  workspace = "7",
})

hl.window_rule({
  match = {
    class = "^(steam)$",
  },
  workspace = "4",
})

hl.window_rule({
  match = {
    class = "^(steam_app_291550)$",
  },
  workspace = "5",
  fullscreen = true,
})

hl.window_rule({
  match = {
    class = "^(xfreerdp)$",
  },
  workspace = "8",
  fullscreen = true,
})
