-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("XF86MonBrightnessUp", hl.dsp.global("caelestia:brightnessUp"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.global("caelestia:brightnessDown"), { locked = true })

hl.bind("Ctrl+Alt + Delete", hl.dsp.global("caelestia:session"))
hl.bind("CTRL + Escape", hl.dsp.global("caelestia:clearNotifs"))

hl.bind("SUPER + R", hl.dsp.global("caelestia:launcher"))
hl.bind("Super+Shift + R", hl.dsp.exec_cmd("qs -c caelestia kill; caelestia shell"))

--#! Session
hl.bind("SUPER + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("Super+Shift + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("Super+Shift + L", hl.dsp.exec_cmd("sleep 0.1 && systemctl suspend || loginctl suspend"), { locked = true })
hl.bind("Ctrl+Shift+Alt+Super + Delete", hl.dsp.exec_cmd("systemctl poweroff || loginctl poweroff"))
