bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown

bind = Ctrl+Alt, Delete, global, caelestia:session
bind = Ctrl, Escape, global, caelestia:clearNotifs

bind = Super, R, global, caelestia:launcher
bind = Super+Shift, R, exec, qs -c caelestia kill; caelestia shell

##! Session
bind = Super, L, exec, loginctl lock-session # Lock
bind = Super+Shift, L, exec, loginctl lock-session
bindl = Super+Shift, L, exec, sleep 0.1 && systemctl suspend || loginctl suspend # Suspend system
bind = Ctrl+Shift+Alt+Super, Delete, exec, systemctl poweroff || loginctl poweroff
