-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness increase"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness decrease"), { locked = true })

hl.bind("CTRL+ALT + Delete", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call sessionMenu toggle"))
hl.bind("CTRL + Escape", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call notifications dismissAll"))

hl.bind("SUPER + R", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))
-- bind = Super+Shift, R, exec, qs -c noctalia-shell kill

hl.bind("SUPER + W", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call wallpaper toggle"))

--#! Session
hl.bind("SUPER + L", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call lockScreen lock"))
