-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("noctalia msg brightness-up"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("noctalia msg brightness-down 5%"), { locked = true })

hl.bind("CTRL+ALT + Delete", hl.dsp.exec_cmd("noctalia msg panel-open session"))
hl.bind("CTRL + Escape", hl.dsp.exec_cmd("noctalia msg notification-clear-active"))

hl.bind("SUPER + R", hl.dsp.exec_cmd("noctalia msg panel-open launcher"))
-- bind = Super+Shift, R, exec, qs -c noctalia-shell kill

hl.bind("SUPER + W", hl.dsp.exec_cmd("noctalia msg panel-open wallpaper"))

--#! Session
hl.bind("SUPER + L", hl.dsp.exec_cmd("noctalia msg session lock"))
