# Host configuration for arch
# Virtual Machine

host: arch
description: Base Config for Miscallaneous usage

# Import shared configurations (optional)
# Example:
# import:
#   - hosts/shared/laptop-common.yaml

# Enabled modules
enabled_modules: [

]

# Host-specific packages
packages: []

# Exclude packages from base or modules
exclude: []

# Settings
flatpak_scope: user
auto_prune: false
backup_tool: timeshift
