-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local primary = "rgb(c3c0ff)"
local surface = "rgb(131316)"
local secondary = "rgb(c7c4dd)"
local error = "rgb(ffb4ab)"
local tertiary = "rgb(eab9d1)"
local surface_lowest = "rgb(0e0e11)"

hl.config({
    general = {
        col = {
            active_border = primary,
            inactive_border = surface,
        },
    },
    group = {
        col = {
            border_active = secondary,
            border_inactive = surface,
            border_locked_active = error,
            border_locked_inactive = surface,
        },
        groupbar = {
            col = {
                active = secondary,
                inactive = surface,
                locked_active = error,
                locked_inactive = surface,
            },
        },
    },
})

