$primary_paletteKeyColor = ac616b
$secondary_paletteKeyColor = 906e71
$tertiary_paletteKeyColor = 937147
$neutral_paletteKeyColor = 817475
$neutral_variant_paletteKeyColor = 847374
$background = 1a1112
$onBackground = f0dedf
$surface = 1a1112
$surfaceDim = 1a1112
$surfaceBright = 413737
$surfaceContainerLowest = 140c0d
$surfaceContainerLow = 22191a
$surfaceContainer = 261d1e
$surfaceContainerHigh = 312828
$surfaceContainerHighest = 3d3233
$onSurface = f0dedf
$surfaceVariant = 524344
$onSurfaceVariant = d7c1c3
$inverseSurface = f0dedf
$inverseOnSurface = 382e2f
$outline = 9f8c8d
$outlineVariant = 524344
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb2bb
$primary = ffb2bb
$onPrimary = 561d27
$primaryContainer = 72333d
$onPrimaryContainer = ffd9dc
$inversePrimary = 8e4953
$secondary = e5bdc0
$onSecondary = 43292c
$secondaryContainer = 5f4144
$onSecondaryContainer = ffd9dc
$tertiary = e9bf8f
$onTertiary = 442b07
$tertiaryContainer = af8a5e
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd9dc
$primaryFixedDim = ffb2bb
$onPrimaryFixed = 3b0713
$onPrimaryFixedVariant = 72333d
$secondaryFixed = ffd9dc
$secondaryFixedDim = e5bdc0
$onSecondaryFixed = 2c1518
$onSecondaryFixedVariant = 5c3f42
$tertiaryFixed = ffddb7
$tertiaryFixedDim = e9bf8f
$onTertiaryFixed = 2a1700
$onTertiaryFixedVariant = 5e411b
$term0 = 353434
$term1 = ff516b
$term2 = ffbcad
$term3 = ffdedb
$term4 = b3a2d5
$term5 = ee8fa1
$term6 = ffba93
$term7 = efd2ce
$term8 = b49e9b
$term9 = ff838e
$term10 = ffd4ca
$term11 = fff1ef
$term12 = dcbc93
$term13 = fda7b4
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffeeed
$flamingo = fed9db
$pink = ffd1da
$mauve = ffa6c4
$red = ff95a6
$maroon = f7aab3
$peach = ffbdbc
$yellow = ffedea
$green = ffd8c5
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = fca1d0
$lavender = ffb9d6
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ca5b83
$kvisitedSelection = ca5b82
$knegative = eb506c
$knegativeSelection = eb506c
$kneutral = ff8789
$kneutralSelection = ff8788
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f0dedf
$subtext1 = d7c1c3
$subtext0 = 9f8c8d
$overlay2 = 8b7a7b
$overlay1 = 776768
$overlay0 = 645657
$surface2 = 524546
$surface1 = 403435
$surface0 = 2d2223
$base = 1a1112
$mantle = 1a1112
$crust = 191011
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
